Theme options added
ISIS3510-202410-Team33/mobile-kotlin pull request #69
Opened 2024-04-25 00:57 UTC by c4ts0up

An inheritable activity is created to use light sensibility theming. Theme options is MVVMized for personal customization. Repositories missing, not indexed in main run, sensor implementation is unefficient. Not fatal, can be improved further on.

2024-04-25 01:25 UTC, Daniel27110 commented
Please implement the repositories and data fetching in the Model before requesting a review. (Also, avoid using terms like 'MVVMized' in the future)

2024-04-25 01:28 UTC, Daniel27110 requested changes
Please implement the repositories and data fetching in the Model before requesting a review. (Also, avoid using terms like 'MVVMized' in the future)

2024-04-26 04:01 UTC, c4ts0up commented
Implemented repositories but had error fetching from the backend

2024-04-26 04:10 UTC, Daniel27110 approved these changes

2024-04-26 04:10 UTC, merged